LineLength:
  Max: 120
AllCops:
  Include:
    - Gemfile
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/EndOfLine:
  EnforcedStyle: lf

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
