language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
cache: bundler
env:
  - DATABASE_URL=postgres://localhost/speedrunracing_test
services:
  - postgresql
before_install:
  - sed -i '2d' Gemfile
before_script:
  - psql -c 'create database speedrunracing_test;' -U postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rspec
