development:
  # required to run dev server
  DATABASE_URL: 
  SRR_TWITCH_CLIENT_ID:
  SRR_TWITCH_CLENT_SECRET:

test:
  # required to be able to run tests
  DATABASE_URL: 

# you don't need to fill out anything past here unless you're deploying this somewhere
production:
  DATABASE_URL:

